---
- hosts: Extra
  remote_user: ubuntu
  become: true
  roles:
     - { role: common,           tags: [ 'common'     ] }
     - { role: php,              tags: [ 'php'        ] }
     - { role: apache,           tags: [ 'apache'     ] }
     - { role: nginx,            tags: [ 'nginx'      ] }
     - { role: mysql,            tags: [ 'mysql'      ] }
     - { role: phpmyadmin,       tags: [ 'phpmyadmin' ] }   
     - { role: mongodb,          tags: [ 'mongodb'    ] }
     - { role: google-chrome,    tags: [ 'chrome'     ] }
     - { role: common_app,       tags: [ 'common_app' ] }
     - { role: prometheus,         tags: [ 'prometheus'] }
     - { role: mongodb-monitoring,         tags: [ 'mongo-prometheus'] } 






