---
## Install System Pakcages and Utils

- name : dpkg --configure -a
  shell : dpkg --configure -a

- name: Install System Pakcages and Utils
  apt: name={{ item }} state=latest update_cache=yes cache_valid_time=5400
  with_items:
   - openssl
   - git
   - git-core
   - golang
   - ruby-compass
   - goaccess
   - htop
   - rsyslog
   - zip
   - vim
   - vim-common
   - curl
   - multitail
   - sysvbanner
   - figlet
   - upstart
   - python-pip
   - python-software-properties
   - logwatch
   - sendmail
   - nfs-common
   - memcached

